manifest:
  version: 1.0
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.0-rc1
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - hal_atmel
        path-prefix: deps/
